# # ── Status bar ────────────────────────────────────────────────────────────────
set -g status-position top
set -g status-justify centre
set -g status-interval 1                       # Refresh the status line every second


# Lavender + Beige Palette
BG="#0D1117"
FG="#E8DCC8"
lavender="#C4B5FD"
lavender_strong="#A78BFA"
lavender_warn="#D8B4FE"
beige_alert="#F5CBA7"
sage_ok="#B7C9A8"
beige_soft="#F0E2D0"
beige_muted="#B8AA97"
border_active="#A78BFA"
border_inactive="#5B5563"
text_dark="#232028"

# Icons
ARROW_RIGHT="#(printf '\uE0B0')"
ARROW_RIGHT_SLIM="#(printf '\uE0B1')"
ARROW_LEFT="#(printf '\uE0B2')"
SLANT_BOTTOM_RIGHT="#(printf '\uE0BA')"
SLANT_BOTTOM_LEFT="#(printf '\uE0B8')"
SLANT_TOP_LEFT="#(printf '\uE0BC')"
SLANT_TOP_RIGHT="#(printf '\uE0BE')"



SEPERATOR="#(printf '\uE0B9')"

# Components
SESSION_BLOCK="\
#[bg=${beige_soft},fg=${text_dark} bold] #(echo ' #S ' | tr '[:lower:]' '[:upper:]') \
#[fg=default,bg=${border_inactive}]${SLANT_BOTTOM_LEFT}\
"
END_BLOCK="\
${SLANT_TOP_RIGHT}\
#[bg=${beige_soft},fg=${text_dark} bold] #[fg=${text_dark} bold italics]%A, %d %b %Y #[fg=${text_dark}]%I:%M %p \
"

#Style
set -g status-left-style NONE
set -g status-right-style NONE
set-option -g window-status-seperator ""

set-option -g status-style bg=${BG},fg=${FG}
set -g message-style "fg=${FG},bg=${BG}"
set -g message-command-style "fg=${FG},bg=${BG}"

set -g pane-border-style "fg=${border_inactive}"
set -g pane-active-border-style "fg=${border_active}"


#Status Bar

## Left
set-option -g status-left-length 100
set-option -g status-left "${SESSION_BLOCK}"
set -ga status-left "\
#[fg=${lavender}] #{?client_prefix,#[fg=#{lavender_warn} bold]PREFIX ,\
#{?#{==:#{pane_mode},copy-mode},#[fg=#{beige_alert} bold]COPY ,\
#[fg=#{sage_ok} bold]NORMAL}} \
#[fg=${border_inactive},bg=default]${SLANT_BOTTOM_LEFT}
"

#Window or Middle
set-option -g window-status-format "\
#[fg=${border_inactive}]${SLANT_BOTTOM_RIGHT}\
#[bg=${border_inactive},fg=${beige_soft} bold] #I \
#[bg=default,fg=${border_inactive}]${SLANT_TOP_LEFT} #[fg=${beige_soft} bold]#W \
"

set-option -g window-status-current-format "\
#[fg=${border_active}]${SLANT_BOTTOM_RIGHT}\
#[bg=${border_active},fg=${text_dark} bold] #I \
#[bg=default,fg=${border_active}]${SLANT_TOP_LEFT} #[fg=${beige_soft} bold]#W \
"

#Right
set-option -g status-right-length 100
set-option status-right "${END_BLOCK}"
