# ── Run catppuccin plugin ─────────────────────────────────────────────────────
run-shell "$HOME/.local/share/tmux/plugins/catppuccin/tmux/catppuccin.tmux"

# # ── Status bar ────────────────────────────────────────────────────────────────
# set -g window-status-separator ""
set -g window-status-separator "#[fg=#{@thm_overlay_0}] > "
set -g status-position top
set -g status-style "bg=default"

set -g window-status-format "#[bg=default,fg=#{@thm_overlay_0}] Tab #I "
set -g window-status-current-format "#[bg=#{@thm_green},fg=#{@thm_base},bold] Tab #I "

set -g status-left-length 100
set -g status-left "#[fg=#{@thm_fg},bold]TMUX (#S) #{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_green} bold]NORMAL }}"

set -g status-right ""
set -g status-right-length 0

# ── Pane borders ──────────────────────────────────────────────────────────────
setw -g pane-border-status off
setw -g pane-active-border-style "bg=default,fg=#{@thm_overlay_2}"
setw -g pane-border-style "bg=default,fg=#{@thm_surface_2}"
setw -g pane-border-lines single
