set -g @catppuccin_flavor "frappe"
set -g @catppuccin_status_background "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_current_number_color "#{@thm_green}"
set -g @catppuccin_window_text " Tab #I "
set -g @catppuccin_window_number ""
set -g @catppuccin_window_current_text " Tab #I "
set -g @catppuccin_window_current_number ""
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_right_separator "#[fg=#{@_ctp_status_bg},reverse]#[none]"
set -g @catppuccin_window_left_separator "#[fg=#{@_ctp_status_bg}]#[none]"
set -g @catppuccin_window_middle_separator "#[bg=#{@catppuccin_window_number_color},fg=#{@catppuccin_window_text_color}]"
set -g @catppuccin_window_current_middle_separator "#[bg=#{@catppuccin_window_current_number_color},fg=#{@catppuccin_window_current_text_color}]"
